### ISSUE TITLE
Which comes first - country or year?

### ISSUE THREAD

**Issue by captainrobbo** [w3c/opentrack-cg#11]
We're building a public registry and  [basing the URLS on this](http://opentrack.run/athlib/build/html/identity.html#url-scheme-and-codes)

For a competition which has been given a short code (e.g. "og" for "Olympic Games"), do people prefer "country before year", or "year before country"?
/x/bra/2016/og
/x/2016/bra/og

**Comment by espinr** [comment]
I would prefer **year** first. So in case we have an event without a unique country (for instance, a country co-organized by several organizers in different countries like those ultra-distance mountain races). Just my opinion.

**Comment by captainrobbo** [comment]
On 2 May 2017 at 15:42, Martin Alvarez-Espinar <notifications@github.com>
wrote:

> I would prefer *year* first. So in case we have an event without a unique
> country (for instance, a country co-organized by several organizers in
> different countries like those ultra-distance mountain races). Just my
> opinion.
>
A good point.    There was a European Masters competition in a tri-border
area recently, with events in 3 countries.

- Andy
