### ISSUE TITLE
Define/use a taxonomy for countries and territories

### ISSUE THREAD

**Issue by espinr** [w3c/opentrack-cg#14]
There are several `Place`s in the model, as well as `PostalAddress`es.  To guarantee interoperability we need to recommend the way to describe **countries**. 

At first sight, I would recommend ISO 3166 codes, but I found that IAAF uses IOC codes that are different. For instance: SLO (IOC) - SVN (ISO3166) for [Slovenia](http://idi.fundacionctic.org/disaster-fp7-skosic/describe?uri=http%3A%2F%2Fpublications.europa.eu%2Fresource%2Fauthority%2Fcountry%2FSVN&lang=en). 

A colleague of mine suggested using a [third schema](http://idi.fundacionctic.org/disaster-fp7-skosic/describe?uri=http%3A%2F%2Fpurl.org%2Femergel%2Fmodules%2523CountryClassification) wich includes both code schemes, also aligned with others such as ITU, NATO, IATA, etc. This could solve some of the problems we have:
* More than countries. Hierarchically we can have countries>regions>counties>cities. 
* Multilingualism. Place names translated into dozens of languages. (e.g. فنلینڈ <- [Finland](http://idi.fundacionctic.org/disaster-fp7-skosic/describe?uri=http%3A%2F%2Fpublications.europa.eu%2Fresource%2Fauthority%2Fcountry%2FFIN&lang=en) in Urdu).   

I have to check if we can customize the list for us. This is, having a easy way to get the code (URI).

**Comment by spitxa** [comment]
i've just created some datasets focusing on the 'administrative' levels of the iaaf, more specifically regional affiliations (i.e. eaa, caa, etc.) [1] & national federations (i.e. gibraltar amateur athletic association) [2].

[1] http://idi.fundacionctic.org/disaster-fp7-skosic/describe?uri=http%3A%2F%2Fpurl.org%2Femergel%2Fmodules%23IAAFRegions&lang=en

[2] http://idi.fundacionctic.org/disaster-fp7-skosic/describe?uri=http%3A%2F%2Fpurl.org%2Femergel%2Fmodules%23EAA_FEDERATION_GIB&lang=en

**Comment by espinr** [comment]
[Country](https://w3c.github.io/opentrack-cg/spec/model/#country) and (Continent)[https://w3c.github.io/opentrack-cg/spec/model/#continent] defined using the EU NAL codes.
