### ISSUE TITLE
Status of Competition

### ISSUE THREAD

**Issue by espinr** [w3c/opentrack-cg#16]
I've listed possible statuses of competitions (https://github.com/w3c/opentrack-cg/blob/master/spec/model/overview.md#event-status).

| Code | Status |
| ---- | ------ |
| `Unscheduled` | Competition is not confirmed. |
| `Scheduled` | Competition is scheduled. |
| `Postponed` | Competition will be postponed without being rescheduled yet. |
| `Rescheduled` | Competition is rescheduled. |
| `Scheduled Break` | Competition has a scheduled break. |
| `Running` | Competition in progress. | 
| `Interrupted` | Competition interrupted once in progress. | 
| `Getting Ready` | The start of the competition is imminent |
| `Finished` | Competition is over and no more action will happen on the field of play (last competitor finished). |
| `Cancelled` | Competition will not take place |
| `Completed` | <mark>???</mark> |

@captainrobbo , I included all from OpenAth. I found that 'Completed' overlaps with 'Finished' (specified by IOC). Can we remove `completed` and use `finished` instead?

**Comment by captainrobbo** [comment]
On 16 May 2017 at 10:47, Martin Alvarez-Espinar <notifications@github.com>
wrote:

> I've listed possible statuses of competitions (https://github.com/w3c/
> opentrack-cg/blob/master/spec/model/overview.md#event-status).
> Code Status
> Unscheduled Competition is not confirmed.
> Scheduled Competition is scheduled.
> Postponed Competition will be postponed without being rescheduled yet.
> Rescheduled Competition is rescheduled.
> Scheduled Break Competition has a scheduled break.
> Running Competition in progress.
> Interrupted Competition interrupted once in progress.
> Getting Ready The start of the competition is imminent
> Finished Competition is over and no more action will happen on the field
> of play (last competitor finished).
> Cancelled Competition will not take place
> Completed ???
>
> @captainrobbo <https://github.com/captainrobbo> , I included all from
> OpenAth. I found that 'Completed' overlaps with 'Finished' (specified by
> IOC). Can we remove completed and use finished instead?
>
> Sure.  We will do a big overhaul of athlib in June to match your models
and codes.

Again, contexts matter.  The above make sense from the viewpoing of a TV
broadcaster.  But to a statistician, or official, or the public looking at
a results website, we need the following concepts at "race level":

 - not yet started (multiple variations are possible from your list)
 - Running
 - Finished but results are being prepared/input
 - Provisional results are available
 - "Official" results - the referee did not disqualify anyone and the
officials are happy.

The distinction between the last two is important.  I wonder if a separate
field "resultsStatus" is a better way to cover it?

- Andy

**Comment by espinr** [comment]
Indeed, I've just created a new set of [result statuses](https://github.com/w3c/opentrack-cg/blob/master/spec/model/overview.md#result-statuses):

| Code | Status |
| ---- | ------ |
| `START_LIST` | Before competition, Start List	|
| `LIVE` | For live updates during competition |
| `INTERMEDIATE` | When competition is stopped, usued at pre-defined points |
| `UNCONFIRMED` | When the unit is over but not yet unofficial or official.	Only used if other statuses do not come quickly.  |
| `UNOFFICIAL` | Results of the competition released as soon as the event is over, not waiting any official decision of the International Federation. The correctness of data must be assured.  |
| `OFFICIAL` | Results of the competition released as soon as the event is officially confirmed taking into account the resolution of the protests, etc.  |
| `PARTIAL` | Incomplete list, Final Ranking. |
| `PROTESTED` | After the competition is no longer LIVE and a protest has been lodged	After all decisions on the protest are made the ResultStatus will change to UNOFFICIAL or OFFICIAL as appropriate.  |
