### ISSUE TITLE
Should we define age categories for youth (below U18)?

### ISSUE THREAD

**Issue by espinr** [w3c/opentrack-cg#5]
In case we define a list of standard age ranges (see #4), should we include those age categories for youth Athletics. IAAF considers U18 (boys and girls aged 16-17) but no more.

There are different rules to set up this classifications depending on body and sport. See this [on the main document](https://github.com/w3c/opentrack-cg/blob/master/spec/model/overview.md#youth).

**Comment by espinr** [comment]
On 12 April, Mirko mentioned that it is also common to find one-year range for youth sports. 
Also, there are different criteria to establish these ranges. For instance, some sports/federations considers age ranges taken into account different birthdays-period (sports season or 1st Jan - 31st Dec). So it's difficult to find a common pattern for youth sports.

My proposal is not defining these categories for youth sports (under U18). Leaving this property as free text.

**Comment by espinr** [comment]
Proposal: 
* Define official known age-range categories.
* Allow adding free text for those special age-range categories

**Comment by captainrobbo** [comment]
I would define the set of rules used at competition level, and just refer to it.  

In most countries, athletics meetings will just say "Under IAAF rules".

For example, if a competition is run "under UK Athletics Rules", that tells us clearly that we will have U13, U15, U17, U20 with particular cutoff dates; that younger kids can do a maximum of 3 events.
we could simply assume that some function exists
     age_group(competition date, birth date...) -> code

The rules of the sport are exhaustively documented and it's easy to cross-refer rather than repeating them in the standard.

**Comment by espinr** [comment]
OK, to refer the set of rules related to the category. Good point.

This function _(age_group(competition date, birth date...) -> code)_ would be perfect but we would need a place and tool where all the available codes are listed. In brief, if my script finds a piece of data with something like { 'code':'U18_IAAF_Male' }, it should be able to refer to the code and infer that this means:
- age-range: Under 18
- Under IAAF rules
- gender: Male

So we could match categories, at least by gender and sex.

In this case, in order to describe that "Category X is under Y rules" (related to the code) and make it interoperable for machines, we would need something like:
```javascript
{
  "@type":"Category",     // This means this instance is of type 'Category'
  "age-range" : "U17",     // 
  "gender" : "Male" ,
  "regulatedBy" : "IAAF"    // @type=>Federation
}
```
Now the problem is producing this exhaustive list of codes. Or just adding them on the fly. 

Ideas? 


If we have a single 

age_group(competition date, birth date...) -> code

**Comment by captainrobbo** [comment]
On 26 April 2017 at 08:56, Martin Alvarez-Espinar <notifications@github.com>
wrote:

>  { 'code':'U18_IAAF_Male' }, it should be able to refer to the code and
> infer that this means:
>
>    - age-range: Under 18
>    - Under IAAF rules
>    - gender: Male
>
>
That's a good code design.  Practically, even if this was in a UK
competition, we could attach an IAAF age group code to it, to tell rankings
sites which category they belonged in.

**Comment by espinr** [comment]
included the official *standard* list of age-ranges (those recognized by IAAF, EA, and WMA). The rest will be specified by open text. For instance: 
```javascript
{
  "description" : "Boys under 13 Mars Years",
  "age-range": "U13",
  "ruledBy": "federation:MARS",
  "gender": "gender:Male"
}
```
