### ISSUE TITLE
To add 'previous name' for athletes

### ISSUE THREAD

**Issue by espinr** [w3c/opentrack-cg#7]
Mirko suggested adding a new property for athletes in case they used another name (e.g., before getting married).

**Comment by espinr** [comment]
Added two new properties:
- PreviousFamilyName
- PreviousGivenName?

**Comment by tripu** [comment]
I think I saw once a good article about best practices to store people's names in computers, but I can't find it now.

[This](http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/) is the closest I could find, but it does not provide answers (only a compendium of things that can go wrong with names).
